### ISSUE TITLE
Remove the commercial book in the starter kit

### ISSUE THREAD

**Issue by MJavadZallaghi** [MahdiGorji98/ros2_AUT_community#1]
You have provided the link to the file of a commercial book (https://github.com/MahdiGorji98/ros2_AUT_community/blob/main/starter%20kit/concise_ROS2). I strictly recommend to remove it.
@MahdiGorji98 
@AVJF1996 
Please only share the materials with a possible public permission.

**Comment by MahdiGorji98** [comment]
done
